<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/* 
ProductRepository
What is repository?
    src/repository/
 */

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    // attributes
    #[ORM\Id]
    #[ORM\GeneratedValue] // id is auto-generated by the database
    #[ORM\Column]

    // this entity is not database table, it is a class

/*     
    we have two kind of ORM:
        1. Laravel ORM
        2. Object Mapping
 */

    
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $stock = null;

/*     so imagine you have a product which should'n be empty
    so if you have a setter, you could empty the product
    so we remove getters and setters and add costum setters and getters
 */

    public function makeUnavailable(): void
    {
        $this->stock = 0;
    } // rich method

    // public function getId(): ?int
    // {
    //     return $this->id;
    // }

    // public function getTitle(): ?string
    // {
    //     return $this->title;
    // }

    // public function setTitle(string $title): self
    // {
    //     $this->title = $title;

    //     return $this;
    // }

    // public function getStock(): ?int
    // {
    //     return $this->stock;
    // }

    // public function setStock(int $stock): self
    // {
    //     $this->stock = $stock;

    //     return $this;
    // }
}
